version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignored_updates:
      - match:
          dependency_name: "org.apache.commons:commons-lang3"
          version_requirement: "[3.8.1,)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
