language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./runSonarQubeAnalysis.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: true
